In [1]:
import pandas as pd
import numpy as np

In [7]:
df_zara=pd.read_csv(r"c:\Users\hp\Downloads\zara (1).csv", sep=";")

# Convertir en Excel
df_zara.to_excel("zara.xlsx", index=False)
# Convertir en Json
df_zara.to_json("zara.json", orient="records", indent=4, force_ascii=False)
df_zara

,Product ID,Product Position,Promotion,Product Category,Seasonal,Sales Volume,brand,url,sku,name,description,price,currency,scraped_at,terms,section
0,185102,Aisle,No,Clothing,No,2823,Zara,https://www.zara.com/us/en/basic-puffer-jacket...,272145190-250-2,BASIC PUFFER JACKET,Puffer jacket made of tear-resistant ripstop f...,19.99,USD,2024-02-19T08:50:05.654618,jackets,MAN
1,188771,Aisle,No,Clothing,No,654,Zara,https://www.zara.com/us/en/tuxedo-jacket-p0889...,324052738-800-46,TUXEDO JACKET,Straight fit blazer. Pointed lapel collar and ...,169.00,USD,2024-02-19T08:50:06.590930,jackets,MAN
2,180176,End-cap,Yes,Clothing,Yes,2220,Zara,https://www.zara.com/us/en/slim-fit-suit-jacke...,335342680-800-44,SLIM FIT SUIT JACKET,Slim fit jacket. Notched lapel collar. Long sl...,129.00,USD,2024-02-19T08:50:07.301419,jackets,MAN
3,112917,Aisle,Yes,Clothing,Yes,1568,Zara,https://www.zara.com/us/en/stretch-suit-jacket...,328303236-420-44,STRETCH SUIT JACKET,Slim fit jacket made of viscose blend fabric. ...,129.00,USD,2024-02-19T08:50:07.882922,jackets,MAN
4,192936,End-cap,No,Clothing,Yes,2942,Zara,https://www.zara.com/us/en/double-faced-jacket...,312368260-800-2,DOUBLE FACED JACKET,Jacket made of faux leather faux shearling wit...,139.00,USD,2024-02-19T08:50:08.453847,jackets,MAN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,159182,Front of Store,Yes,Clothing,No,1014,Zara,https://www.zara.com/us/en/basic-100-wool-swea...,321993245-500-2,FAUX LEATHER OVERSIZED JACKET LIMITED EDITION,Jacket made of technical fabric with padded in...,169.00,USD,2024-02-19T09:10:43.883037,jackets,MAN
248,199233,Aisle,Yes,Clothing,No,2222,Zara,https://www.zara.com/us/en/colorblock-knit-cro...,330590505-500-2,CONTRASTING PATCHES BOMBER JACKET,Oversized jacket. Notched lapel collar and lon...,159.00,USD,2024-02-19T09:10:44.463883,jackets,MAN
249,137044,Aisle,No,Clothing,Yes,2534,Zara,https://www.zara.com/us/en/hooded-technical-ja...,320680326-107-39,PATCH BOMBER JACKET,Varsity jacket with elastic collar and long sl...,12.99,USD,2024-02-19T09:10:45.009106,jackets,MAN
250,154736,Front of Store,Yes,Clothing,Yes,1466,Zara,https://www.zara.com/us/en/houndstooth-suit-ja...,311292244-800-39,CROPPED BOMBER JACKET LIMITED EDITION,Varsity jacket with padded interior. Rib elast...,19.90,USD,2024-02-19T09:10:45.631804,jackets,MAN
251,141434,Front of Store,No,Clothing,Yes,2870,Zara,https://www.zara.com/us/en/bomber-jacket-p0534...,311307610-400-39,FAUX LEATHER PUFFER JACKET,Jacket with lightly padded interior. Rib colla...,39.90,USD,2024-02-19T09:10:31.877972,jackets,MAN

In [8]:
df_zara.describe(include="all")

,Product ID,Product Position,Promotion,Product Category,Seasonal,Sales Volume,brand,url,sku,name,description,price,currency,scraped_at,terms,section
count,252.000000,252,252,252,252,252.000000,252,252,252,251,250,252.000000,252,252,252,252
unique,NaN,3,2,1,2,NaN,1,228,228,194,221,NaN,1,229,5,2
top,NaN,Aisle,No,Clothing,Yes,NaN,Zara,https://www.zara.com/us/en/hooded-technical-ja...,318209963-800-2,PLAID OVERSHIRT,Varsity jacket with elastic collar and long sl...,NaN,USD,2024-02-19T09:10:34.521463,jackets,MAN
freq,NaN,97,132,252,128,NaN,252,2,2,6,4,NaN,252,2,140,218
mean,153370.503968,NaN,NaN,NaN,NaN,1823.702381,NaN,NaN,NaN,NaN,NaN,86.252540,NaN,NaN,NaN,NaN
std,26160.444549,NaN,NaN,NaN,NaN,697.703748,NaN,NaN,NaN,NaN,NaN,52.083205,NaN,NaN,NaN,NaN
min,110075.000000,NaN,NaN,NaN,NaN,529.000000,NaN,NaN,NaN,NaN,NaN,7.990000,NaN,NaN,NaN,NaN
25%,131053.750000,NaN,NaN,NaN,NaN,1243.000000,NaN,NaN,NaN,NaN,NaN,49.900000,NaN,NaN,NaN,NaN
50%,151681.500000,NaN,NaN,NaN,NaN,1839.500000,NaN,NaN,NaN,NaN,NaN,79.900000,NaN,NaN,NaN,NaN
75%,175669.750000,NaN,NaN,NaN,NaN,2398.750000,NaN,NaN,NaN,NaN,NaN,109.000000,NaN,NaN,NaN,NaN
max,199631.000000,NaN,NaN,NaN,NaN,2989.000000,NaN,NaN,NaN,NaN,NaN,439.000000,NaN,NaN,NaN,NaN

In [9]:
df_zara_copy = df_zara.copy()

In [10]:
df_zara_copy_num = df_zara_copy.select_dtypes(include="number")
df_zara_copy_num.columns

Index(['Product ID', 'Sales Volume', 'price'], dtype='object')

In [11]:
df_zara_copy_ctg = df_zara_copy.select_dtypes(exclude="number")

In [13]:
df_zara_copy_ctg.mode()

,Product Position,Promotion,Product Category,Seasonal,brand,url,sku,name,description,currency,scraped_at,terms,section
0,Aisle,No,Clothing,Yes,Zara,https://www.zara.com/us/en/alpaca-blend-open-k...,281593208-015-2,PLAID OVERSHIRT,Varsity jacket with elastic collar and long sl...,USD,2024-02-19T09:10:31.877971,jackets,MAN
1,NaN,NaN,NaN,NaN,NaN,https://www.zara.com/us/en/basic-100-wool-swea...,281883711-071-2,NaN,NaN,NaN,2024-02-19T09:10:32.534246,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,https://www.zara.com/us/en/basic-foil-knit-swe...,311282631-712-2,NaN,NaN,NaN,2024-02-19T09:10:33.128884,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,https://www.zara.com/us/en/basic-knit-sweater-...,311292244-800-39,NaN,NaN,NaN,2024-02-19T09:10:33.890995,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,https://www.zara.com/us/en/bomber-jacket-p0534...,311307610-400-39,NaN,NaN,NaN,2024-02-19T09:10:34.521463,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,https://www.zara.com/us/en/colorblock-knit-cro...,312571093-710-2,NaN,NaN,NaN,2024-02-19T09:10:35.068338,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,https://www.zara.com/us/en/contrast-topstitchi...,312978838-611-2,NaN,NaN,NaN,2024-02-19T09:10:35.641404,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,https://www.zara.com/us/en/faux-fur-jewel-swea...,313008692-514-2,NaN,NaN,NaN,2024-02-19T09:10:36.152051,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,https://www.zara.com/us/en/fine-knit-crop-swea...,313027279-800-2,NaN,NaN,NaN,2024-02-19T09:10:36.839166,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,https://www.zara.com/us/en/foil-knit-crop-swea...,314937772-710-2,NaN,NaN,NaN,2024-02-19T09:10:37.484871,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,https://www.zara.com/us/en/gathered-waist-knit...,316727555-700-2,NaN,NaN,NaN,2024-02-19T09:10:38.362632,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,https://www.zara.com/us/en/hooded-technical-ja...,318209963-800-2,NaN,NaN,NaN,2024-02-19T09:10:38.884024,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,https://www.zara.com/us/en/houndstooth-suit-ja...,320026789-714-2,NaN,NaN,NaN,2024-02-19T09:10:39.415761,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,https://www.zara.com/us/en/jewel-knit-sweater-...,320278659-251-2,NaN,NaN,NaN,2024-02-19T09:10:39.911179,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,https://www.zara.com/us/en/knit-sweater-with-b...,320671529-802-2,NaN,NaN,NaN,2024-02-19T09:10:40.681401,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,https://www.zara.com/us/en/knit-sweater-with-p...,320680326-107-39,NaN,NaN,NaN,2024-02-19T09:10:41.519426,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,https://www.zara.com/us/en/knit-sweater-with-r...,321993245-500-2,NaN,NaN,NaN,2024-02-19T09:10:42.016223,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,https://www.zara.com/us/en/knit-v-neck-sweater...,322612356-505-2,NaN,NaN,NaN,2024-02-19T09:10:42.593244,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,https://www.zara.com/us/en/metal-bead-knit-swe...,323216360-406-2,NaN,NaN,NaN,2024-02-19T09:10:43.379668,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,https://www.zara.com/us/en/oversized-knit-swea...,323646471-802-2,NaN,NaN,NaN,2024-02-19T09:10:43.883037,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,https://www.zara.com/us/en/soft-jewel-sweater-...,329282612-401-2,NaN,NaN,NaN,2024-02-19T09:10:44.463883,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,https://www.zara.com/us/en/striped-crop-knit-s...,330290387-401-2,NaN,NaN,NaN,2024-02-19T09:10:45.009106,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,https://www.zara.com/us/en/v-neck-knit-sweater...,330590505-500-2,NaN,NaN,NaN,2024-02-19T09:10:45.631804,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,https://www.zara.com/us/en/wool-blend-knit-swe...,336446858-822-2,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df_zara_copy_num.mean()

Product ID      153370.503968
Sales Volume      1823.702381
price               86.252540
dtype: float64

In [17]:
df_zara_copy_num.median()

Product ID      151681.5
Sales Volume      1839.5
price               79.9
dtype: float64

In [18]:
df_zara_copy_num.mode()

     Product ID  Sales Volume  price
0        110075        1466.0   89.9
1        110295           NaN    NaN
2        110329           NaN    NaN
3        110805           NaN    NaN
4        111521           NaN    NaN
..          ...           ...    ...
247      198375           NaN    NaN
248      199233           NaN    NaN
249      199279           NaN    NaN
250      199368           NaN    NaN
251      199631           NaN    NaN

[252 rows x 3 columns]

In [21]:
etendue = df_zara_copy_num.max() - df_zara_copy_num.min()
print(etendue)

Product ID      89556.00
Sales Volume     2460.00
price             431.01
dtype: float64

In [22]:

df_zara_copy_num.var()

Product ID      6.843689e+08
Sales Volume    4.867905e+05
price           2.712660e+03
dtype: float64

In [23]:
df_zara_copy_num.std

<bound method DataFrame.std of      Product ID  Sales Volume   price
0        185102          2823   19.99
1        188771           654  169.00
2        180176          2220  129.00
3        112917          1568  129.00
4        192936          2942  139.00
..          ...           ...     ...
247      159182          1014  169.00
248      199233          2222  159.00
249      137044          2534   12.99
250      154736          1466   19.90
251      141434          2870   39.90

[252 rows x 3 columns]>

In [24]:
df_zara_copy_num.quantile([0.25, 0.5, 0.75])

      Product ID  Sales Volume  price
0.25   131053.75       1243.00   49.9
0.50   151681.50       1839.50   79.9
0.75   175669.75       2398.75  109.0

In [27]:

IQR = df_zara_copy_num.quantile(0.75)-df_zara_copy_num.quantile(0.25)
print(IQR)

Product ID      44616.00
Sales Volume     1155.75
price              59.10
dtype: float64

In [28]:
cov_matrice=df_zara_copy_num.cov()
print(cov_matrice)

                Product ID  Sales Volume          price
Product ID    6.843689e+08 -2.197917e+06 -100583.842122
Sales Volume -2.197917e+06  4.867905e+05   -2593.075456
price        -1.005838e+05 -2.593075e+03    2712.660199

In [29]:
corr_matrix = df_zara_copy_num.corr()
print(corr_matrix)

              Product ID  Sales Volume     price
Product ID      1.000000     -0.120419 -0.073822
Sales Volume   -0.120419      1.000000 -0.071359
price          -0.073822     -0.071359  1.000000

In [30]:
df_zara_copy_mq=df_zara_copy.dropna()

In [31]:
df_zara_copy_mq.isna().sum()

Product ID          0
Product Position    0
Promotion           0
Product Category    0
Seasonal            0
Sales Volume        0
brand               0
url                 0
sku                 0
name                0
description         0
price               0
currency            0
scraped_at          0
terms               0
section             0
dtype: int64

In [32]:
df_zara_copy_mq.to_csv("zara_apres_traitement.csv")